apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
  - name: web
    image: felicia009/dockerhub_felicia:latest
    imagePullPolicy: Always
    ports:
      - containerPort: 80

